### ISSUE TITLE
Uncaught TypeError: (0 , _workerized_filter_cities__WEBPACK_IMPORTED_MODULE_2__.getItems) is not a function 

### ISSUE THREAD

**Issue by ACPK** [kentcdodds/react-performance#120]
RE: https://github.com/kentcdodds/react-performance/issues/115

I'm using the most recent version of the code and am having trouble moving forward with "4. React.memo for Reducing re-renders".

What are your thoughts on adding a note to the course letting people know that this section may not work?

**Comment by kentcdodds** [comment]
Hi @ACPK! I'm sorry you're experiencing issues. I thought I had added a note, but maybe it could be in a better spot. Would you be interested in making a PR to add a note where you think people would notice?

**Comment by ACPK** [comment]
@kentcdodds Absolutely. How do I find the code for https://epicreact.dev/modules/react-performance/reactmemo-for-reducing-re-renders-intro so I know of the bug when watching the intro video?

**Comment by paul-ilies** [comment]
@ACPK  console.log allItems in filter-cities.js and should solve the problem

**Comment by ACPK** [comment]
That doesn’t actually fix the issue if you close the server and the restart it. You then have to remove the console.log() to get it working. On Nov 4, 2022, at 4:04 AM, ILIES PAUL DANIEL ***@***.***> wrote:﻿
@ACPK  console.log allItems in filter-cities.js and should solve the problem

**Comment by ACPK** [comment]
@paul-ilies You get the error if restart the server after including console.log() as mentioned in https://github.com/kentcdodds/react-performance/issues/115
